package dto;
// Generated 26/11/2016 08:01:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,catalog="mydb"
)
public class Administrador  implements java.io.Serializable {


     private AdministradorId id;
     private String nombre;
     private String apellido;
     private String estado;
     private String telefono;
     private String celular;
     private String correo;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Administrador() {
    }

	
    public Administrador(AdministradorId id, String nombre, String apellido, String estado, String correo) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.estado = estado;
        this.correo = correo;
    }
    public Administrador(AdministradorId id, String nombre, String apellido, String estado, String telefono, String celular, String correo, Set<Curso> cursos) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.estado = estado;
       this.telefono = telefono;
       this.celular = celular;
       this.correo = correo;
       this.cursos = cursos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tipoDocumento", column=@Column(name="Tipo_Documento", nullable=false, length=5) ), 
        @AttributeOverride(name="documento", column=@Column(name="Documento", nullable=false, length=45) ) } )
    public AdministradorId getId() {
        return this.id;
    }
    
    public void setId(AdministradorId id) {
        this.id = id;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Estado", nullable=false, length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="Telefono", length=25)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Celular", length=25)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="Correo", nullable=false, length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="administrador")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


