package dto;
// Generated 26/11/2016 08:01:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsistenciaId generated by hbm2java
 */
@Embeddable
public class AsistenciaId  implements java.io.Serializable {


     private String estudianteTipoDocumento;
     private String estudianteDocumento;
     private int claseIdClase;
     private int claseGrupoCursoIdCurso;
     private int claseGrupoIdGrupo;

    public AsistenciaId() {
    }

    public AsistenciaId(String estudianteTipoDocumento, String estudianteDocumento, int claseIdClase, int claseGrupoCursoIdCurso, int claseGrupoIdGrupo) {
       this.estudianteTipoDocumento = estudianteTipoDocumento;
       this.estudianteDocumento = estudianteDocumento;
       this.claseIdClase = claseIdClase;
       this.claseGrupoCursoIdCurso = claseGrupoCursoIdCurso;
       this.claseGrupoIdGrupo = claseGrupoIdGrupo;
    }
   


    @Column(name="Estudiante_Tipo_Documento", nullable=false, length=5)
    public String getEstudianteTipoDocumento() {
        return this.estudianteTipoDocumento;
    }
    
    public void setEstudianteTipoDocumento(String estudianteTipoDocumento) {
        this.estudianteTipoDocumento = estudianteTipoDocumento;
    }


    @Column(name="Estudiante_Documento", nullable=false, length=45)
    public String getEstudianteDocumento() {
        return this.estudianteDocumento;
    }
    
    public void setEstudianteDocumento(String estudianteDocumento) {
        this.estudianteDocumento = estudianteDocumento;
    }


    @Column(name="Clase_idClase", nullable=false)
    public int getClaseIdClase() {
        return this.claseIdClase;
    }
    
    public void setClaseIdClase(int claseIdClase) {
        this.claseIdClase = claseIdClase;
    }


    @Column(name="Clase_Grupo_Curso_id_Curso", nullable=false)
    public int getClaseGrupoCursoIdCurso() {
        return this.claseGrupoCursoIdCurso;
    }
    
    public void setClaseGrupoCursoIdCurso(int claseGrupoCursoIdCurso) {
        this.claseGrupoCursoIdCurso = claseGrupoCursoIdCurso;
    }


    @Column(name="Clase_Grupo_idGrupo", nullable=false)
    public int getClaseGrupoIdGrupo() {
        return this.claseGrupoIdGrupo;
    }
    
    public void setClaseGrupoIdGrupo(int claseGrupoIdGrupo) {
        this.claseGrupoIdGrupo = claseGrupoIdGrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsistenciaId) ) return false;
		 AsistenciaId castOther = ( AsistenciaId ) other; 
         
		 return ( (this.getEstudianteTipoDocumento()==castOther.getEstudianteTipoDocumento()) || ( this.getEstudianteTipoDocumento()!=null && castOther.getEstudianteTipoDocumento()!=null && this.getEstudianteTipoDocumento().equals(castOther.getEstudianteTipoDocumento()) ) )
 && ( (this.getEstudianteDocumento()==castOther.getEstudianteDocumento()) || ( this.getEstudianteDocumento()!=null && castOther.getEstudianteDocumento()!=null && this.getEstudianteDocumento().equals(castOther.getEstudianteDocumento()) ) )
 && (this.getClaseIdClase()==castOther.getClaseIdClase())
 && (this.getClaseGrupoCursoIdCurso()==castOther.getClaseGrupoCursoIdCurso())
 && (this.getClaseGrupoIdGrupo()==castOther.getClaseGrupoIdGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEstudianteTipoDocumento() == null ? 0 : this.getEstudianteTipoDocumento().hashCode() );
         result = 37 * result + ( getEstudianteDocumento() == null ? 0 : this.getEstudianteDocumento().hashCode() );
         result = 37 * result + this.getClaseIdClase();
         result = 37 * result + this.getClaseGrupoCursoIdCurso();
         result = 37 * result + this.getClaseGrupoIdGrupo();
         return result;
   }   


}


