package dto;
// Generated 26/11/2016 08:01:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Matricula generated by hbm2java
 */
@Entity
@Table(name="matricula"
    ,catalog="mydb"
)
public class Matricula  implements java.io.Serializable {


     private Integer radicado;
     private Curso curso;
     private Estudiante estudiante;
     private Date fechaInscripcion;

    public Matricula() {
    }

    public Matricula(Curso curso, Estudiante estudiante, Date fechaInscripcion) {
       this.curso = curso;
       this.estudiante = estudiante;
       this.fechaInscripcion = fechaInscripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Radicado", unique=true, nullable=false)
    public Integer getRadicado() {
        return this.radicado;
    }
    
    public void setRadicado(Integer radicado) {
        this.radicado = radicado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Curso_id_Curso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Estudiante_Tipo_Documento", referencedColumnName="Tipo_Documento", nullable=false), 
        @JoinColumn(name="Estudiante_Documento", referencedColumnName="Documento", nullable=false) } )
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Inscripcion", nullable=false, length=19)
    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }
    
    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }




}


