package dto;
// Generated 26/11/2016 08:01:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Requisito generated by hbm2java
 */
@Entity
@Table(name="requisito"
    ,catalog="mydb"
)
public class Requisito  implements java.io.Serializable {


     private Integer idRequisito;
     private String descripcion;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Requisito() {
    }

	
    public Requisito(String descripcion) {
        this.descripcion = descripcion;
    }
    public Requisito(String descripcion, Set<Curso> cursos) {
       this.descripcion = descripcion;
       this.cursos = cursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRequisito", unique=true, nullable=false)
    public Integer getIdRequisito() {
        return this.idRequisito;
    }
    
    public void setIdRequisito(Integer idRequisito) {
        this.idRequisito = idRequisito;
    }

    
    @Column(name="Descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="requisito")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


